// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dolmadrbridefentuzyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbG1hZHJicmlkZWZlbnR1enlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjcwMTMsImV4cCI6MjA1ODYwMzAxM30.2Za-1GzDcnqhKniKb4cbmSq112yqwY-FdCe-MhWJ3LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);